### ISSUE TITLE
match problem

### ISSUE THREAD

**Issue by eroux** [buda-base/lucene-sa#19]
not sure what the options of the 84000 analyzer are, but searching `Maitreyapraṇidhana` doesn't find `Maitreyapraṇidhanarāja`. It should be fairly easy to create a (failing) unit test for that specific case, @sten1ee do you think you could do that?

**Comment by sten1ee** [comment]
Yes, @eroux, I'll get right on it.

**Comment by sten1ee** [comment]
Ahem.
My test results are somehow discrepant with the ones we got through eXist.
The only part of the config that (I see) differs is the scorer - eXist supplies a custom one:
```text
Searching for phrase 'Maitreya­praṇidhana', parsed query looks like: '(matin treya dana)'
  scored 0.89 on doc[4] 'Maitreyapraṇidhana'
  scored 0.89 on doc[5] 'Maitreya­praṇidhana'
  scored 0.89 on doc[6] 'Maitreya­praṇidhana­rāja'
  scored 0.89 on doc[8] 'Maitreyapraṇidhanarāja'
  scored 0.89 on doc[9] 'Maitreyaṇidhana'
  scored 0.78 on doc[7] 'maitreyapra[mukhas]ṇidhana'
  scored 0.30 on doc[1] 'maitreyapraṇid'
  scored 0.30 on doc[2] 'Maitreyapraṇid'
  scored 0.30 on doc[3] 'MaitreyaPraṇid'
```

**Comment by eroux** [comment]
master branch is ok yes. I don't really know the eXist scorer, it seems a bit odd that this gives a very different result though... there's something a bit fishy about `(matin treya dana)`, what's the configuration of the analyzer that you're using? (on both exist and your test)

**Comment by sten1ee** [comment]
The eXist config is as follows:
```xml
            <analyzer id="sa-ltn:index" class="io.bdrc.lucene.sa.SanskritAnalyzer">
                <param name="mode" type="java.lang.String" value="syl"/>
                <param name="inputEncoding" type="java.lang.String" value="roman"/>
                <param name="mergePrepositions" type="boolean" value="false"/>
                <param name="filterGeminates" type="boolean" value="true"/>
                <param name="lenient" type="java.lang.String" value="index"/>
            </analyzer>
            
            <analyzer id="sa-ltn:query" class="io.bdrc.lucene.sa.SanskritAnalyzer">
                <param name="mode" type="java.lang.String" value="syl"/>
                <param name="inputEncoding" type="java.lang.String" value="roman"/>
                <param name="mergePrepositions" type="boolean" value="false"/>
                <param name="filterGeminates" type="boolean" value="false"/>
                <param name="lenient" type="java.lang.String" value="query"/>
            </analyzer>
```

And the the test case's analyzers are configured by this set of constants:
```java
    static class AnalyzerArgs {
        final Version version = LuceneVersion;
        final String  mode = "word";
        final String  inputEncoding = "roman";
        final Boolean mergePrepositions = false;
        final Boolean indexFilterGeminates = true;
        final Boolean queryFilterGeminates = false;
        final String  indexLenient = "index";
        final String  queryLenient = "query";
    }
```

**Comment by sten1ee** [comment]
Ouch!
I saw it as I pasted it -- mode = "word"

**Comment by sten1ee** [comment]
Ok, now this is more like it:
```text
Searching for phrase 'Maitreya­praṇidhana', parsed query looks like: '(mai tre ya da na)'
  scored 1.07 on doc[4] 'Maitreyapraṇidhana'                                                                              
  scored 1.07 on doc[5] 'Maitreya­praṇidhana'                                                                             
  scored 1.07 on doc[9] 'Maitreyaṇidhana'                                                                                 
  scored 0.91 on doc[6] 'Maitreya­praṇidhana­rāja'                                                                        
  scored 0.76 on doc[7] 'maitreyapra[mukhas]ṇidhana'                                                                      
  scored 0.49 on doc[8] 'Maitreyapraṇidhanarāja'                                                                          
  scored 0.30 on doc[1] 'maitreyapraṇid'                                                                                  
  scored 0.30 on doc[2] 'Maitreyapraṇid'                                                                                  
  scored 0.30 on doc[3] 'MaitreyaPraṇid'                                                                                  
```

**Comment by eroux** [comment]
ok, that's more what I would expect... so the first surprise is that `­praṇi` disappeared from the query (`mai tre ya da na`), is there a list of stop words? (I think it should be one of the arguments)

**Comment by sten1ee** [comment]
No explicit list of stop words, so I my guess is the default one is used, and yes, it is:
```
[main] INFO io.bdrc.lucene.sa.CommonHelpers - found resource /skrt-stopwords.txt through regular classloader
```

**Comment by eroux** [comment]
ok, can you remove the stop words? (I can't remember how to do that exactly)

**Comment by sten1ee** [comment]
with empty skrt-stopwords.txt file:
```
Searching for phrase 'Maitreya­praṇidhana', parsed query looks like: '(mai tre ya pra ni da na)'
  scored 1.09 on doc[4] 'Maitreyapraṇidhana'                                                                                                   
  scored 1.09 on doc[5] 'Maitreya­praṇidhana'                                                                                                  
  scored 0.91 on doc[6] 'Maitreya­praṇidhana­rāja'                                                                                             
  scored 0.91 on doc[7] 'maitreyapra[mukhas]ṇidhana'                                                                                           
  scored 0.83 on doc[9] 'Maitreyaṇidhana'                                                                                                      
  scored 0.60 on doc[8] 'Maitreyapraṇidhanarāja'                                                                                               
  scored 0.29 on doc[1] 'maitreyapraṇid'                                                                                                       
  scored 0.29 on doc[2] 'Maitreyapraṇid'                                                                                                       
  scored 0.29 on doc[3] 'MaitreyaPraṇid'
```

**Comment by eroux** [comment]
ok, that looks good to me... if it looks good to you too, can you configure the analyzer in exide so that it doesn't use a stopword list?

**Comment by sten1ee** [comment]
Yes,
although there's no way to do it changing the eXist Analyzer(s) config only.
I either have to build the jar with an empty stopwords file (the easier way)
*or*
tweak/add a chain of c-tors that provide option for no stopwords (at present there's no such option).
I think I'd go for the former option, if you don't mind.
Oh, cr*p - but then I won't be able to use this config for the test case ...
So, it seems the only sensible option to achieve it is: in addition to 
```java
SanskritAnalyzer(org.apache.lucene.util.Version version, String mode, String inputEncoding, Boolean mergePrepositions, Boolean filterGeminates, String lenient) throws IOException
```
have also a
```java
SanskritAnalyzer(org.apache.lucene.util.Version version, String mode, String inputEncoding, Boolean mergePrepositions, Boolean filterGeminates, String lenient, String stopwordsFileName) throws IOException
```
where passing a null file name switches off the stopwords filtering.
How do you like it (despite the fact that such a monstrous constructor looks ugly, for sure)

**Comment by eroux** [comment]
I thought there was an option already sorry, yes please add an option... another idea is to just force the stopwords to be null in the case of a syllable analyzer, it's probably easier but also less flexible. Can you implement the additional argument in master?

**Comment by sten1ee** [comment]
Yes, I almost did that in a slightly different manner; Will create a PR for you to review shortly.
Meanwhile, I realised that there is a TC that fails (in master) (when running the tests within IntelliJ)
It is in FullLuceneShowcase.java, line 110, method testWordLenientSearch(): "Expected :0  Actual   :1"
What's bothering me is that the code in the failing test initialises it Analyzers like this:
```java
        // indexing in words, from iast, with stopwords
        Analyzer indexingAnalyzer = new SanskritAnalyzer("word", "roman", true, false, "index");
        // querying in words, from SLP, with stopwords  
        Analyzer queryingAnalyzer = new SanskritAnalyzer("space", "roman", false, false, "query");
```
while the README.md states that lenient word mode it *should* be initialised like this
```code
Indexing: SanskritAnalyzer("word", "roman", false, true, "index")
Querying: SanskritAnalyzer("space", "roman", false, false, "query")
```

I've noticed that the next TC - ```testSylLenientSearch()``` - although passing, also violates the initialisation form of lenient syl mode of the Index analyzer by supplying 'false, false' instead of 'true, false'

Why that discrepancy between doc and tests?

**Comment by eroux** [comment]
I honestly cannot remember... maybe it was to test some edge cases... but in any case, the tests should probably be fixed

**Comment by sten1ee** [comment]
I will 'fix' them, just wanted you to review the situation and say whether the initialisation in the tests should follow the doc.
i.e. documentation on lenient search is correct and should be followed in this TCs?

**Comment by eroux** [comment]
right, the doc seems correct in that case, thanks for spotting!

**Comment by eroux** [comment]
the issue still exists but in another form
