### ISSUE TITLE
nara not segmented in syllables

### ISSUE THREAD

**Issue by eroux** [buda-base/lucene-sa#23]
See [this test](https://github.com/buda-base/lucene-sa/blob/b8a5b9d5faad6defe1b9dc77493ae8154adf15cf/src/test/java/io/bdrc/lucene/sa/TestSyllableTokenizer.java#L89)

**Comment by eroux** [comment]
@sten1ee do you manage to debug the code? If you're really stuck tell me

**Comment by sten1ee** [comment]
@eroux since my last comment on PR22 yesterday, I've managed to put 1.5 hours into debugging it.
I've also simplified the TC into this one: (which hopefully is still a valid TC?)
```java
        String input = "narāja";
        Reader reader = new StringReader(input);
        SanskritAnalyzer sa = new SanskritAnalyzer("syl", "roman", false, true, "index");
        List<String> expected = Arrays.asList("na", "ra", "ja");
        ...
```
No result yet.

**Comment by eroux** [comment]
ok, no problem

**Comment by sten1ee** [comment]
@eroux, after 15-20 mins of debugging I realised that in this particular case, if 'r' was considered a CONSONANT (instead of VOWEL in Lenient mode) this particular problem will be gone;
Then I replaced those two lines:
```java
	addToMap((int)'r', CONSONANT, false);
	addToMap((int)'r', VOWEL, true);
```
with this line:
```java
	addToMap((int)'r', CONSONANT);
```
No TC started to fail as a result of this change, while the 'Maitreya­praṇidhana' started passing.
I know nothing about Sanskrit and thus - about the SanskritAnalyzer and its companion classes, but I suggest we either apply this fix, or someone add a TC that would pass prior to that fix, and would fail after it (AKA "TDD")

**Comment by eroux** [comment]
yes, that's what I thought. But let's think of it a bit more and add a test with `saṃskṛtam`, in this case the r is a vowel (you can see it with the diacritics). 

Ideally it should be found when searching either `samskritam` (most of the time the vowel `ṛ` will be searched as `ri`), `samskrtam` and `saṃskṛtam`.

I think if you apply your fix it won't be the case anymore. I think one way to improve the situation would be to make a special treatment for the `r` in lenient mode: when followed by a vowel other than `i`, it should be considered a consonant, otherwise a vowel.

Then we'll get another problem but I don't think it can be solved: most of the time `ri` in lenient mode represents `ṛ` (where r is a vowel), but sometimes it can represents `ri` where `r` is a consonant... I'm not sure how to treat that but that can be for another iteration...

**Comment by sten1ee** [comment]
If I knew something about Sanskrit, I'd ask:
_Pardon me, but how could an 'r' be a VOWEL in Lenient mode and a CONSONANT otherwise?_
🤸‍♀

**Comment by eroux** [comment]
see my answer above, the current thinking (which I propose we adjust a bit) is that `r` in lenient mode represents `ṛ` which is a vowel. It's more of a semi-vowel where there a sort of a i/u that's not voiced a lot at the same time as an `r` (or just after). So it sounds like `/ri/` or `/ru/`. My example would be rendered `samskritam` in English phonetics (which is more or less what lenient mode is), it means "Sanskrit".

**Comment by eroux** [comment]
here's an example of the problem we can't solve in lenient mode: `rikta` has a consonant `r`, while `ṛksāma` has a vowel `r`. The indexer can easily make the difference because it can access the diacritics. But the difficulty here is on the query side of things: when someone searches for `rik` in lenient mode, we can't know if we're looking for a consonant `r` or a vowel `ṛ`. In that case I think `ri` should be treated in lenient mode as if it was always `ṛ`... I think that should work.

**Comment by eroux** [comment]
@sten1ee any update? If you don't think you can fix it tell me, I'll try to find some time

**Comment by sten1ee** [comment]
@eroux: I haven't touched that issue since then, (switched to eXist related
tasks).
 Are you suggesting that the map (char -> Consonant|Vowel) should be
differentiated not only by lenient/non-lenient mode, but by
Indexinq/Querying too?

**Comment by eroux** [comment]
hmm not really, my suggestion is more that the categorization of r as a vowel or consonant in lenient mode should depend on the letter after it

**Comment by sten1ee** [comment]
Ah, I see.
Sorry for having to repeat it.
(Some sort of excuse is: _Out of all the things I have lost, I miss my mind the most._ ― Mark Twain)

I did not answer your question: _If you don't think you can fix it tell me, I'll try to find some time_
For the time being I can't fix it; I guess I've become too old to be a proper Java programmer anymore; Or it is Ruby's fault - after I've learned it (to some degree) my mind rigorously objects any attempts to make it comprehend methods having Cyclomatic complexity > _certain threshold_, (which threshold is more often than not crossed in standard java code).
So yeah, if it's not too much of a burden for you and you find the time - fix it, please Elie.
If not -- I will try to tackle it when it is escalated or something.

**Comment by eroux** [comment]
ok, no problem!

**Comment by eroux** [comment]
@sten1ee I think I'm done, can you try? I also did a relatively neat normalization of anusvara and ignored visargas, maybe it will change some other results (for the better theoretically!)

**Comment by sten1ee** [comment]
(not that I understand it, but) it looks great, Élie! Thank you.
Only the exact target score on ```testSearchMaitreyapraṇidhana()``` are somehow different for me.
I posted a comment to the relevant src change, but for the sake of better documentation, I'll paste it here as well.
For me the exact (target) scores are as follows:
```
	doc=0 score=1.5970155
	doc=1 score=1.5970155
	doc=2 score=0.39325747
	doc=3 score=0.39325747
	doc=4 score=0.39325747
	doc=5 score=1.7897819
	doc=6 score=1.7897819
	doc=7 score=1.7150962
```

**Comment by eroux** [comment]
I'm ready to make a release, are you planning to do further testings or should I make the release now?

**Comment by sten1ee** [comment]
Okay, no plans for further tests.
**Fire at will**

**Comment by eroux** [comment]
ok, done, thanks!
